//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace Wonderland.Logic.PostcodeAnywhere.RetrieveById {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://services.postcodeanywhere.co.uk/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RetrieveByIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Wonderland.Logic.Properties.Settings.Default.Wonderland_Logic_RetrieveById_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RetrieveByIdCompletedEventHandler RetrieveByIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RetrieveById", RequestElementName="SoapRequest", RequestNamespace="http://services.postcodeanywhere.co.uk/", ResponseElementName="Response", ResponseNamespace="http://services.postcodeanywhere.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Results[] RetrieveById(string Key, string Id, string PreferredLanguage, string UserName) {
            object[] results = this.Invoke("RetrieveById", new object[] {
                        Key,
                        Id,
                        PreferredLanguage,
                        UserName});
            return ((Results[])(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveByIdAsync(string Key, string Id, string PreferredLanguage, string UserName) {
            this.RetrieveByIdAsync(Key, Id, PreferredLanguage, UserName, null);
        }
        
        /// <remarks/>
        public void RetrieveByIdAsync(string Key, string Id, string PreferredLanguage, string UserName, object userState) {
            if ((this.RetrieveByIdOperationCompleted == null)) {
                this.RetrieveByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveByIdOperationCompleted);
            }
            this.InvokeAsync("RetrieveById", new object[] {
                        Key,
                        Id,
                        PreferredLanguage,
                        UserName}, this.RetrieveByIdOperationCompleted, userState);
        }
        
        private void OnRetrieveByIdOperationCompleted(object arg) {
            if ((this.RetrieveByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveByIdCompleted(this, new RetrieveByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.postcodeanywhere.co.uk/")]
    public partial class Results {
        
        private int udprnField;
        
        private string companyField;
        
        private string departmentField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string line3Field;
        
        private string line4Field;
        
        private string line5Field;
        
        private string postTownField;
        
        private string countyField;
        
        private string postcodeField;
        
        private int mailsortField;
        
        private string barcodeField;
        
        private string typeField;
        
        private string deliveryPointSuffixField;
        
        private string subBuildingField;
        
        private string buildingNameField;
        
        private string buildingNumberField;
        
        private string primaryStreetField;
        
        private string secondaryStreetField;
        
        private string doubleDependentLocalityField;
        
        private string dependentLocalityField;
        
        private string poBoxField;
        
        private string primaryStreetNameField;
        
        private string primaryStreetTypeField;
        
        private string secondaryStreetNameField;
        
        private string secondaryStreetTypeField;
        
        private string countryNameField;
        
        private string countryISO2Field;
        
        private string countryISO3Field;
        
        /// <remarks/>
        public int Udprn {
            get {
                return this.udprnField;
            }
            set {
                this.udprnField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        public string Line3 {
            get {
                return this.line3Field;
            }
            set {
                this.line3Field = value;
            }
        }
        
        /// <remarks/>
        public string Line4 {
            get {
                return this.line4Field;
            }
            set {
                this.line4Field = value;
            }
        }
        
        /// <remarks/>
        public string Line5 {
            get {
                return this.line5Field;
            }
            set {
                this.line5Field = value;
            }
        }
        
        /// <remarks/>
        public string PostTown {
            get {
                return this.postTownField;
            }
            set {
                this.postTownField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public int Mailsort {
            get {
                return this.mailsortField;
            }
            set {
                this.mailsortField = value;
            }
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryPointSuffix {
            get {
                return this.deliveryPointSuffixField;
            }
            set {
                this.deliveryPointSuffixField = value;
            }
        }
        
        /// <remarks/>
        public string SubBuilding {
            get {
                return this.subBuildingField;
            }
            set {
                this.subBuildingField = value;
            }
        }
        
        /// <remarks/>
        public string BuildingName {
            get {
                return this.buildingNameField;
            }
            set {
                this.buildingNameField = value;
            }
        }
        
        /// <remarks/>
        public string BuildingNumber {
            get {
                return this.buildingNumberField;
            }
            set {
                this.buildingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryStreet {
            get {
                return this.primaryStreetField;
            }
            set {
                this.primaryStreetField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryStreet {
            get {
                return this.secondaryStreetField;
            }
            set {
                this.secondaryStreetField = value;
            }
        }
        
        /// <remarks/>
        public string DoubleDependentLocality {
            get {
                return this.doubleDependentLocalityField;
            }
            set {
                this.doubleDependentLocalityField = value;
            }
        }
        
        /// <remarks/>
        public string DependentLocality {
            get {
                return this.dependentLocalityField;
            }
            set {
                this.dependentLocalityField = value;
            }
        }
        
        /// <remarks/>
        public string PoBox {
            get {
                return this.poBoxField;
            }
            set {
                this.poBoxField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryStreetName {
            get {
                return this.primaryStreetNameField;
            }
            set {
                this.primaryStreetNameField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryStreetType {
            get {
                return this.primaryStreetTypeField;
            }
            set {
                this.primaryStreetTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryStreetName {
            get {
                return this.secondaryStreetNameField;
            }
            set {
                this.secondaryStreetNameField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryStreetType {
            get {
                return this.secondaryStreetTypeField;
            }
            set {
                this.secondaryStreetTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public string CountryISO2 {
            get {
                return this.countryISO2Field;
            }
            set {
                this.countryISO2Field = value;
            }
        }
        
        /// <remarks/>
        public string CountryISO3 {
            get {
                return this.countryISO3Field;
            }
            set {
                this.countryISO3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RetrieveByIdCompletedEventHandler(object sender, RetrieveByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Results[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Results[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591