
namespace Wonderland.Logic.SagePay
{
    /// <summary>
    /// Response received from a transaction registration
    /// </summary>
    public class TransactionRegistrationResponse
    {
        public TransactionRegistrationResponse()
        {
            this.Status = TransactionRegistrationStatus.ERROR;
        }

        /// <summary>
        /// Protocol version
        /// </summary>
        public string VPSProtocol { get; set; }

        ///// <summary>
        ///// Status
        ///// </summary>
        public TransactionRegistrationStatus Status { get; set; }

        /// <summary>
        /// Additional status details
        /// </summary>
        public string StatusDetail { get; set; }

        /// <summary>
        /// Transaction ID generated by SagePay
        /// </summary>
        public string VPSTxId { get; set; }

        /// <summary>
        /// Security Key
        /// </summary>
        public string SecurityKey { get; set; }

        /// <summary>
        /// Redirect URL
        /// </summary>
        public string NextURL { get; set; }
    }
}
